//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voltaire.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("voltaire.Resources.AppResources.fr", typeof(AppResources_fr).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string AddContact {
            get {
                return ResourceManager.GetString("AddContact", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        internal static string SearchContact {
            get {
                return ResourceManager.GetString("SearchContact", resourceCulture);
            }
        }
        
        internal static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        internal static string TopSalesman {
            get {
                return ResourceManager.GetString("TopSalesman", resourceCulture);
            }
        }
        
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        internal static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        internal static string PartnerGrade {
            get {
                return ResourceManager.GetString("PartnerGrade", resourceCulture);
            }
        }
        
        internal static string ResetFilters {
            get {
                return ResourceManager.GetString("ResetFilters", resourceCulture);
            }
        }
        
        internal static string ParentPartner {
            get {
                return ResourceManager.GetString("ParentPartner", resourceCulture);
            }
        }
        
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        internal static string Quotations {
            get {
                return ResourceManager.GetString("Quotations", resourceCulture);
            }
        }
        
        internal static string Quotation {
            get {
                return ResourceManager.GetString("Quotation", resourceCulture);
            }
        }
        
        internal static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        internal static string LastVisit {
            get {
                return ResourceManager.GetString("LastVisit", resourceCulture);
            }
        }
        
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        internal static string addtags {
            get {
                return ResourceManager.GetString("addtags", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        internal static string RiderHeader {
            get {
                return ResourceManager.GetString("RiderHeader", resourceCulture);
            }
        }
        
        internal static string OrderN {
            get {
                return ResourceManager.GetString("OrderN", resourceCulture);
            }
        }
        
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        internal static string GeneratePDF {
            get {
                return ResourceManager.GetString("GeneratePDF", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        internal static string Salesmens {
            get {
                return ResourceManager.GetString("Salesmens", resourceCulture);
            }
        }
        
        internal static string Salesman {
            get {
                return ResourceManager.GetString("Salesman", resourceCulture);
            }
        }
        
        internal static string SearchSalesman {
            get {
                return ResourceManager.GetString("SearchSalesman", resourceCulture);
            }
        }
        
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        internal static string Leaderboards {
            get {
                return ResourceManager.GetString("Leaderboards", resourceCulture);
            }
        }
        
        internal static string SalesTitle {
            get {
                return ResourceManager.GetString("SalesTitle", resourceCulture);
            }
        }
        
        internal static string CheckIns {
            get {
                return ResourceManager.GetString("CheckIns", resourceCulture);
            }
        }
        
        internal static string LocationEnableAlert {
            get {
                return ResourceManager.GetString("LocationEnableAlert", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string NotNow {
            get {
                return ResourceManager.GetString("NotNow", resourceCulture);
            }
        }
        
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        internal static string RetrospectiveCourse {
            get {
                return ResourceManager.GetString("RetrospectiveCourse", resourceCulture);
            }
        }
        
        internal static string PickStartEnd {
            get {
                return ResourceManager.GetString("PickStartEnd", resourceCulture);
            }
        }
        
        internal static string ChooseFilter {
            get {
                return ResourceManager.GetString("ChooseFilter", resourceCulture);
            }
        }
        
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        internal static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        internal static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        internal static string CoursesDetails {
            get {
                return ResourceManager.GetString("CoursesDetails", resourceCulture);
            }
        }
        
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        internal static string SelectACustomer {
            get {
                return ResourceManager.GetString("SelectACustomer", resourceCulture);
            }
        }
        
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        internal static string PermanentNote {
            get {
                return ResourceManager.GetString("PermanentNote", resourceCulture);
            }
        }
        
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        internal static string SignedDate {
            get {
                return ResourceManager.GetString("SignedDate", resourceCulture);
            }
        }
        
        internal static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        internal static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        internal static string PermanentNotes {
            get {
                return ResourceManager.GetString("PermanentNotes", resourceCulture);
            }
        }
        
        internal static string InternalNotes {
            get {
                return ResourceManager.GetString("InternalNotes", resourceCulture);
            }
        }
        
        internal static string DeleteQuotation {
            get {
                return ResourceManager.GetString("DeleteQuotation", resourceCulture);
            }
        }
        
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        internal static string Permanent {
            get {
                return ResourceManager.GetString("Permanent", resourceCulture);
            }
        }
        
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        internal static string WriteAMesage {
            get {
                return ResourceManager.GetString("WriteAMesage", resourceCulture);
            }
        }
        
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        internal static string PaymentInfo {
            get {
                return ResourceManager.GetString("PaymentInfo", resourceCulture);
            }
        }
        
        internal static string AddTagsTitle {
            get {
                return ResourceManager.GetString("AddTagsTitle", resourceCulture);
            }
        }
        
        internal static string SelectTag {
            get {
                return ResourceManager.GetString("SelectTag", resourceCulture);
            }
        }
        
        internal static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        internal static string Titles {
            get {
                return ResourceManager.GetString("Titles", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        internal static string NewReminder {
            get {
                return ResourceManager.GetString("NewReminder", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        internal static string UsernameMissing {
            get {
                return ResourceManager.GetString("UsernameMissing", resourceCulture);
            }
        }
        
        internal static string PasswordMissing {
            get {
                return ResourceManager.GetString("PasswordMissing", resourceCulture);
            }
        }
        
        internal static string InformationMissing {
            get {
                return ResourceManager.GetString("InformationMissing", resourceCulture);
            }
        }
        
        internal static string IncorrectInfo {
            get {
                return ResourceManager.GetString("IncorrectInfo", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        internal static string LogOutMessage {
            get {
                return ResourceManager.GetString("LogOutMessage", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string FetchingData {
            get {
                return ResourceManager.GetString("FetchingData", resourceCulture);
            }
        }
        
        internal static string Refreshing {
            get {
                return ResourceManager.GetString("Refreshing", resourceCulture);
            }
        }
        
        internal static string SingingIn {
            get {
                return ResourceManager.GetString("SingingIn", resourceCulture);
            }
        }
        
        internal static string SyncingData {
            get {
                return ResourceManager.GetString("SyncingData", resourceCulture);
            }
        }
        
        internal static string NewContact {
            get {
                return ResourceManager.GetString("NewContact", resourceCulture);
            }
        }
        
        internal static string FillInCustomerName {
            get {
                return ResourceManager.GetString("FillInCustomerName", resourceCulture);
            }
        }
        
        internal static string FillInCompanyName {
            get {
                return ResourceManager.GetString("FillInCompanyName", resourceCulture);
            }
        }
        
        internal static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        internal static string MatchingSearch {
            get {
                return ResourceManager.GetString("MatchingSearch", resourceCulture);
            }
        }
        
        internal static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        internal static string SearchPartner {
            get {
                return ResourceManager.GetString("SearchPartner", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        internal static string NoCustomerFound {
            get {
                return ResourceManager.GetString("NoCustomerFound", resourceCulture);
            }
        }
        
        internal static string MessageInternalError {
            get {
                return ResourceManager.GetString("MessageInternalError", resourceCulture);
            }
        }
        
        internal static string FillInformation {
            get {
                return ResourceManager.GetString("FillInformation", resourceCulture);
            }
        }
        
        internal static string EnterOrderNumber {
            get {
                return ResourceManager.GetString("EnterOrderNumber", resourceCulture);
            }
        }
        
        internal static string NewContractFor {
            get {
                return ResourceManager.GetString("NewContractFor", resourceCulture);
            }
        }
        
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        internal static string GivenCombination {
            get {
                return ResourceManager.GetString("GivenCombination", resourceCulture);
            }
        }
        
        internal static string ChooseAnotherOne {
            get {
                return ResourceManager.GetString("ChooseAnotherOne", resourceCulture);
            }
        }
        
        internal static string SelectGrained {
            get {
                return ResourceManager.GetString("SelectGrained", resourceCulture);
            }
        }
        
        internal static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        internal static string JustAMoment {
            get {
                return ResourceManager.GetString("JustAMoment", resourceCulture);
            }
        }
        
        internal static string WantToSendNow {
            get {
                return ResourceManager.GetString("WantToSendNow", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string SendingMail {
            get {
                return ResourceManager.GetString("SendingMail", resourceCulture);
            }
        }
        
        internal static string DocumentSent {
            get {
                return ResourceManager.GetString("DocumentSent", resourceCulture);
            }
        }
        
        internal static string TermsConditions {
            get {
                return ResourceManager.GetString("TermsConditions", resourceCulture);
            }
        }
        
        internal static string AcceptTCForQuotation {
            get {
                return ResourceManager.GetString("AcceptTCForQuotation", resourceCulture);
            }
        }
        
        internal static string AlreadySigned {
            get {
                return ResourceManager.GetString("AlreadySigned", resourceCulture);
            }
        }
        
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        internal static string SignQuoatationFirst {
            get {
                return ResourceManager.GetString("SignQuoatationFirst", resourceCulture);
            }
        }
        
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        internal static string Street1 {
            get {
                return ResourceManager.GetString("Street1", resourceCulture);
            }
        }
        
        internal static string Street2 {
            get {
                return ResourceManager.GetString("Street2", resourceCulture);
            }
        }
        
        internal static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
        
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        internal static string AppSyncing {
            get {
                return ResourceManager.GetString("AppSyncing", resourceCulture);
            }
        }
        
        internal static string AddContract {
            get {
                return ResourceManager.GetString("AddContract", resourceCulture);
            }
        }
        
        internal static string SearchSpace {
            get {
                return ResourceManager.GetString("SearchSpace", resourceCulture);
            }
        }
        
        internal static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        internal static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        internal static string ToDoList {
            get {
                return ResourceManager.GetString("ToDoList", resourceCulture);
            }
        }
        
        internal static string RetrospectiveAgenda {
            get {
                return ResourceManager.GetString("RetrospectiveAgenda", resourceCulture);
            }
        }
        
        internal static string PeriodFrom {
            get {
                return ResourceManager.GetString("PeriodFrom", resourceCulture);
            }
        }
        
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        internal static string SearchArea {
            get {
                return ResourceManager.GetString("SearchArea", resourceCulture);
            }
        }
        
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        internal static string TaxApply {
            get {
                return ResourceManager.GetString("TaxApply", resourceCulture);
            }
        }
        
        internal static string TaxFree {
            get {
                return ResourceManager.GetString("TaxFree", resourceCulture);
            }
        }
        
        internal static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        internal static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        internal static string Trainer {
            get {
                return ResourceManager.GetString("Trainer", resourceCulture);
            }
        }
        
        internal static string HorseShow {
            get {
                return ResourceManager.GetString("HorseShow", resourceCulture);
            }
        }
        
        internal static string QuotationName {
            get {
                return ResourceManager.GetString("QuotationName", resourceCulture);
            }
        }
        
        internal static string AddQuotation {
            get {
                return ResourceManager.GetString("AddQuotation", resourceCulture);
            }
        }
        
        internal static string REF {
            get {
                return ResourceManager.GetString("REF", resourceCulture);
            }
        }
        
        internal static string SaveProduct {
            get {
                return ResourceManager.GetString("SaveProduct", resourceCulture);
            }
        }
        
        internal static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string ProceedSigning {
            get {
                return ResourceManager.GetString("ProceedSigning", resourceCulture);
            }
        }
        
        internal static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        internal static string ExpressOrder {
            get {
                return ResourceManager.GetString("ExpressOrder", resourceCulture);
            }
        }
        
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        internal static string IReadTerms {
            get {
                return ResourceManager.GetString("IReadTerms", resourceCulture);
            }
        }
        
        internal static string LTermsConditions {
            get {
                return ResourceManager.GetString("LTermsConditions", resourceCulture);
            }
        }
        
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        internal static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        internal static string SelectAProduct {
            get {
                return ResourceManager.GetString("SelectAProduct", resourceCulture);
            }
        }
        
        internal static string RemindOnThisDay {
            get {
                return ResourceManager.GetString("RemindOnThisDay", resourceCulture);
            }
        }
        
        internal static string AtSpace {
            get {
                return ResourceManager.GetString("AtSpace", resourceCulture);
            }
        }
        
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        internal static string Terms1 {
            get {
                return ResourceManager.GetString("Terms1", resourceCulture);
            }
        }
        
        internal static string Terms2 {
            get {
                return ResourceManager.GetString("Terms2", resourceCulture);
            }
        }
        
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        internal static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        internal static string CurrentLocation {
            get {
                return ResourceManager.GetString("CurrentLocation", resourceCulture);
            }
        }
        
        internal static string P_Model {
            get {
                return ResourceManager.GetString("P_Model", resourceCulture);
            }
        }
        
        internal static string P_Color {
            get {
                return ResourceManager.GetString("P_Color", resourceCulture);
            }
        }
        
        internal static string P_Leather {
            get {
                return ResourceManager.GetString("P_Leather", resourceCulture);
            }
        }
        
        internal static string P_Grained {
            get {
                return ResourceManager.GetString("P_Grained", resourceCulture);
            }
        }
        
        internal static string P_UnitPrice {
            get {
                return ResourceManager.GetString("P_UnitPrice", resourceCulture);
            }
        }
        
        internal static string P_RiderName {
            get {
                return ResourceManager.GetString("P_RiderName", resourceCulture);
            }
        }
        
        internal static string P_Seat {
            get {
                return ResourceManager.GetString("P_Seat", resourceCulture);
            }
        }
        
        internal static string P_Tree {
            get {
                return ResourceManager.GetString("P_Tree", resourceCulture);
            }
        }
        
        internal static string P_Flaps {
            get {
                return ResourceManager.GetString("P_Flaps", resourceCulture);
            }
        }
        
        internal static string P_2ndSkin {
            get {
                return ResourceManager.GetString("P_2ndSkin", resourceCulture);
            }
        }
        
        internal static string P_RBQgrained {
            get {
                return ResourceManager.GetString("P_RBQgrained", resourceCulture);
            }
        }
        
        internal static string P_FrontBlock {
            get {
                return ResourceManager.GetString("P_FrontBlock", resourceCulture);
            }
        }
        
        internal static string P_RearBlock {
            get {
                return ResourceManager.GetString("P_RearBlock", resourceCulture);
            }
        }
        
        internal static string P_PanelBase {
            get {
                return ResourceManager.GetString("P_PanelBase", resourceCulture);
            }
        }
        
        internal static string P_Comments {
            get {
                return ResourceManager.GetString("P_Comments", resourceCulture);
            }
        }
        
        internal static string P_NamePlate {
            get {
                return ResourceManager.GetString("P_NamePlate", resourceCulture);
            }
        }
        
        internal static string P_Greasing {
            get {
                return ResourceManager.GetString("P_Greasing", resourceCulture);
            }
        }
        
        internal static string P_SpSaddle {
            get {
                return ResourceManager.GetString("P_SpSaddle", resourceCulture);
            }
        }
        
        internal static string P_Note {
            get {
                return ResourceManager.GetString("P_Note", resourceCulture);
            }
        }
        
        internal static string P_Saddle {
            get {
                return ResourceManager.GetString("P_Saddle", resourceCulture);
            }
        }
        
        internal static string P_Accessory {
            get {
                return ResourceManager.GetString("P_Accessory", resourceCulture);
            }
        }
        
        internal static string P_ParentCategory {
            get {
                return ResourceManager.GetString("P_ParentCategory", resourceCulture);
            }
        }
        
        internal static string P_Category {
            get {
                return ResourceManager.GetString("P_Category", resourceCulture);
            }
        }
        
        internal static string P_Reference {
            get {
                return ResourceManager.GetString("P_Reference", resourceCulture);
            }
        }
        
        internal static string P_Service {
            get {
                return ResourceManager.GetString("P_Service", resourceCulture);
            }
        }
        
        internal static string P_Serial_number {
            get {
                return ResourceManager.GetString("P_Serial number", resourceCulture);
            }
        }
        
        internal static string P_Brand {
            get {
                return ResourceManager.GetString("P_Brand", resourceCulture);
            }
        }
        
        internal static string P_Seatsize {
            get {
                return ResourceManager.GetString("P_Seatsize", resourceCulture);
            }
        }
        
        internal static string P_Flapsize {
            get {
                return ResourceManager.GetString("P_Flapsize", resourceCulture);
            }
        }
        
        internal static string P_Other {
            get {
                return ResourceManager.GetString("P_Other", resourceCulture);
            }
        }
        
        internal static string P_Price {
            get {
                return ResourceManager.GetString("P_Price", resourceCulture);
            }
        }
        
        internal static string P_Description {
            get {
                return ResourceManager.GetString("P_Description", resourceCulture);
            }
        }
        
        internal static string P_Size {
            get {
                return ResourceManager.GetString("P_Size", resourceCulture);
            }
        }
        
        internal static string P_Blocks {
            get {
                return ResourceManager.GetString("P_Blocks", resourceCulture);
            }
        }
        
        internal static string P_Discount {
            get {
                return ResourceManager.GetString("P_Discount", resourceCulture);
            }
        }
        
        internal static string P_TradeIn {
            get {
                return ResourceManager.GetString("P_TradeIn", resourceCulture);
            }
        }
        
        internal static string P_ServiceCategory {
            get {
                return ResourceManager.GetString("P_ServiceCategory", resourceCulture);
            }
        }
        
        internal static string P_AfterSale {
            get {
                return ResourceManager.GetString("P_AfterSale", resourceCulture);
            }
        }
        
        internal static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        internal static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        internal static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        internal static string Prescriber {
            get {
                return ResourceManager.GetString("Prescriber", resourceCulture);
            }
        }
        
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        internal static string PaymentNote {
            get {
                return ResourceManager.GetString("PaymentNote", resourceCulture);
            }
        }
        
        internal static string TotalHT {
            get {
                return ResourceManager.GetString("TotalHT", resourceCulture);
            }
        }
        
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        internal static string Taxes {
            get {
                return ResourceManager.GetString("Taxes", resourceCulture);
            }
        }
        
        internal static string TaxPercent {
            get {
                return ResourceManager.GetString("TaxPercent", resourceCulture);
            }
        }
        
        internal static string ShippingCost {
            get {
                return ResourceManager.GetString("ShippingCost", resourceCulture);
            }
        }
        
        internal static string TotalTTC {
            get {
                return ResourceManager.GetString("TotalTTC", resourceCulture);
            }
        }
        
        internal static string SelectShipping {
            get {
                return ResourceManager.GetString("SelectShipping", resourceCulture);
            }
        }
    }
}
