//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voltaire.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("voltaire.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        internal static string SearchContact {
            get {
                return ResourceManager.GetString("SearchContact", resourceCulture);
            }
        }
        
        internal static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        internal static string TopSalesman {
            get {
                return ResourceManager.GetString("TopSalesman", resourceCulture);
            }
        }
        
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        internal static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        internal static string PartnerGrade {
            get {
                return ResourceManager.GetString("PartnerGrade", resourceCulture);
            }
        }
        
        internal static string ResetFilters {
            get {
                return ResourceManager.GetString("ResetFilters", resourceCulture);
            }
        }
        
        internal static string ParentPartner {
            get {
                return ResourceManager.GetString("ParentPartner", resourceCulture);
            }
        }
        
        internal static string LastVisit {
            get {
                return ResourceManager.GetString("LastVisit", resourceCulture);
            }
        }
        
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        internal static string Quotations {
            get {
                return ResourceManager.GetString("Quotations", resourceCulture);
            }
        }
        
        internal static string Quotation {
            get {
                return ResourceManager.GetString("Quotation", resourceCulture);
            }
        }
        
        internal static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        internal static string addtags {
            get {
                return ResourceManager.GetString("addtags", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        internal static string RiderHeader {
            get {
                return ResourceManager.GetString("RiderHeader", resourceCulture);
            }
        }
        
        internal static string OrderN {
            get {
                return ResourceManager.GetString("OrderN", resourceCulture);
            }
        }
        
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        internal static string GeneratePDF {
            get {
                return ResourceManager.GetString("GeneratePDF", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        internal static string Salesmens {
            get {
                return ResourceManager.GetString("Salesmens", resourceCulture);
            }
        }
        
        internal static string Salesman {
            get {
                return ResourceManager.GetString("Salesman", resourceCulture);
            }
        }
        
        internal static string SearchSalesman {
            get {
                return ResourceManager.GetString("SearchSalesman", resourceCulture);
            }
        }
        
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        internal static string Leaderboards {
            get {
                return ResourceManager.GetString("Leaderboards", resourceCulture);
            }
        }
        
        internal static string SalesTitle {
            get {
                return ResourceManager.GetString("SalesTitle", resourceCulture);
            }
        }
        
        internal static string CheckIns {
            get {
                return ResourceManager.GetString("CheckIns", resourceCulture);
            }
        }
        
        internal static string LocationEnableAlert {
            get {
                return ResourceManager.GetString("LocationEnableAlert", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string NotNow {
            get {
                return ResourceManager.GetString("NotNow", resourceCulture);
            }
        }
        
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        internal static string RetrospectiveCourse {
            get {
                return ResourceManager.GetString("RetrospectiveCourse", resourceCulture);
            }
        }
        
        internal static string PickStartEnd {
            get {
                return ResourceManager.GetString("PickStartEnd", resourceCulture);
            }
        }
        
        internal static string ChooseFilter {
            get {
                return ResourceManager.GetString("ChooseFilter", resourceCulture);
            }
        }
        
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        internal static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        internal static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        internal static string CoursesDetails {
            get {
                return ResourceManager.GetString("CoursesDetails", resourceCulture);
            }
        }
        
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        internal static string SelectACustomer {
            get {
                return ResourceManager.GetString("SelectACustomer", resourceCulture);
            }
        }
        
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        internal static string PermanentNote {
            get {
                return ResourceManager.GetString("PermanentNote", resourceCulture);
            }
        }
        
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        internal static string SignedDate {
            get {
                return ResourceManager.GetString("SignedDate", resourceCulture);
            }
        }
        
        internal static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        internal static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        internal static string PermanentNotes {
            get {
                return ResourceManager.GetString("PermanentNotes", resourceCulture);
            }
        }
        
        internal static string InternalNotes {
            get {
                return ResourceManager.GetString("InternalNotes", resourceCulture);
            }
        }
        
        internal static string DeleteQuotation {
            get {
                return ResourceManager.GetString("DeleteQuotation", resourceCulture);
            }
        }
        
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        internal static string Permanent {
            get {
                return ResourceManager.GetString("Permanent", resourceCulture);
            }
        }
        
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        internal static string WriteAMesage {
            get {
                return ResourceManager.GetString("WriteAMesage", resourceCulture);
            }
        }
        
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        internal static string PaymentInfo {
            get {
                return ResourceManager.GetString("PaymentInfo", resourceCulture);
            }
        }
        
        internal static string AddTagsTitle {
            get {
                return ResourceManager.GetString("AddTagsTitle", resourceCulture);
            }
        }
        
        internal static string SelectTag {
            get {
                return ResourceManager.GetString("SelectTag", resourceCulture);
            }
        }
        
        internal static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        internal static string Titles {
            get {
                return ResourceManager.GetString("Titles", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        internal static string NewReminder {
            get {
                return ResourceManager.GetString("NewReminder", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        internal static string UsernameMissing {
            get {
                return ResourceManager.GetString("UsernameMissing", resourceCulture);
            }
        }
        
        internal static string PasswordMissing {
            get {
                return ResourceManager.GetString("PasswordMissing", resourceCulture);
            }
        }
        
        internal static string InformationMissing {
            get {
                return ResourceManager.GetString("InformationMissing", resourceCulture);
            }
        }
        
        internal static string IncorrectInfo {
            get {
                return ResourceManager.GetString("IncorrectInfo", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        internal static string LogOutMessage {
            get {
                return ResourceManager.GetString("LogOutMessage", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string FetchingData {
            get {
                return ResourceManager.GetString("FetchingData", resourceCulture);
            }
        }
        
        internal static string Refreshing {
            get {
                return ResourceManager.GetString("Refreshing", resourceCulture);
            }
        }
        
        internal static string SingingIn {
            get {
                return ResourceManager.GetString("SingingIn", resourceCulture);
            }
        }
        
        internal static string SyncingData {
            get {
                return ResourceManager.GetString("SyncingData", resourceCulture);
            }
        }
        
        internal static string NewContact {
            get {
                return ResourceManager.GetString("NewContact", resourceCulture);
            }
        }
        
        internal static string FillInCustomerName {
            get {
                return ResourceManager.GetString("FillInCustomerName", resourceCulture);
            }
        }
        
        internal static string FillInCompanyName {
            get {
                return ResourceManager.GetString("FillInCompanyName", resourceCulture);
            }
        }
        
        internal static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        internal static string MatchingSearch {
            get {
                return ResourceManager.GetString("MatchingSearch", resourceCulture);
            }
        }
        
        internal static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        internal static string SearchPartner {
            get {
                return ResourceManager.GetString("SearchPartner", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        internal static string NoCustomerFound {
            get {
                return ResourceManager.GetString("NoCustomerFound", resourceCulture);
            }
        }
        
        internal static string MessageInternalError {
            get {
                return ResourceManager.GetString("MessageInternalError", resourceCulture);
            }
        }
        
        internal static string FillInformation {
            get {
                return ResourceManager.GetString("FillInformation", resourceCulture);
            }
        }
        
        internal static string EnterOrderNumber {
            get {
                return ResourceManager.GetString("EnterOrderNumber", resourceCulture);
            }
        }
        
        internal static string NewContractFor {
            get {
                return ResourceManager.GetString("NewContractFor", resourceCulture);
            }
        }
        
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        internal static string GivenCombination {
            get {
                return ResourceManager.GetString("GivenCombination", resourceCulture);
            }
        }
        
        internal static string ChooseAnotherOne {
            get {
                return ResourceManager.GetString("ChooseAnotherOne", resourceCulture);
            }
        }
        
        internal static string SelectGrained {
            get {
                return ResourceManager.GetString("SelectGrained", resourceCulture);
            }
        }
        
        internal static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        internal static string JustAMoment {
            get {
                return ResourceManager.GetString("JustAMoment", resourceCulture);
            }
        }
        
        internal static string WantToSendNow {
            get {
                return ResourceManager.GetString("WantToSendNow", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string SendingMail {
            get {
                return ResourceManager.GetString("SendingMail", resourceCulture);
            }
        }
        
        internal static string DocumentSent {
            get {
                return ResourceManager.GetString("DocumentSent", resourceCulture);
            }
        }
        
        internal static string TermsConditions {
            get {
                return ResourceManager.GetString("TermsConditions", resourceCulture);
            }
        }
        
        internal static string AcceptTCForQuotation {
            get {
                return ResourceManager.GetString("AcceptTCForQuotation", resourceCulture);
            }
        }
        
        internal static string AlreadySigned {
            get {
                return ResourceManager.GetString("AlreadySigned", resourceCulture);
            }
        }
        
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        internal static string SignQuoatationFirst {
            get {
                return ResourceManager.GetString("SignQuoatationFirst", resourceCulture);
            }
        }
        
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        internal static string Street1 {
            get {
                return ResourceManager.GetString("Street1", resourceCulture);
            }
        }
        
        internal static string Street2 {
            get {
                return ResourceManager.GetString("Street2", resourceCulture);
            }
        }
        
        internal static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
        
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        internal static string AppSyncing {
            get {
                return ResourceManager.GetString("AppSyncing", resourceCulture);
            }
        }
        
        internal static string AddContract {
            get {
                return ResourceManager.GetString("AddContract", resourceCulture);
            }
        }
        
        internal static string SearchSpace {
            get {
                return ResourceManager.GetString("SearchSpace", resourceCulture);
            }
        }
        
        internal static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        internal static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        internal static string ToDoList {
            get {
                return ResourceManager.GetString("ToDoList", resourceCulture);
            }
        }
        
        internal static string RetrospectiveAgenda {
            get {
                return ResourceManager.GetString("RetrospectiveAgenda", resourceCulture);
            }
        }
        
        internal static string PeriodFrom {
            get {
                return ResourceManager.GetString("PeriodFrom", resourceCulture);
            }
        }
        
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        internal static string SearchArea {
            get {
                return ResourceManager.GetString("SearchArea", resourceCulture);
            }
        }
        
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
    }
}
